### ISSUE TITLE
Error of texture inpainting

### ISSUE THREAD

**Issue by hygenie1228** [ZhanxyR/SHERT#2]
Hi, thanks for sharing great work!!

I'm currently running your codes based on examples/demo_image
The inpaint result is weirder than expected.
<img width="993" alt="image" src="https://github.com/ZhanxyR/SHERT/assets/69622221/1e878962-63e3-49a3-bdf1-1d0959f2b3fb">
<img width="647" alt="image" src="https://github.com/ZhanxyR/SHERT/assets/69622221/638e357e-fda7-4369-ba1e-b40ffef03994">

Have you ever encountered a similar issue? 
I wanna verify that I did it the right way.
I used local client for inpainting, as described in README.

**Comment by ZhanxyR** [comment]
At first, the textured result shown in Meshlab seems inconsistent with your output. Please check whether to correctly set the output result as the texture image. As for the quality, it is hard to obtain a perfect result with single inpainting. While the inpainting results shown in our paper are obtained with multiple interactive generation, which is mentioned in the SupMat (G.6. and Figure S8).
Another problem in this example is the misalignment of the human face, which we solved by replace it with the predicted result of EMOCA (also shown in Figure S8).

**Comment by hygenie1228** [comment]
Oh, I attached the wrong corresponding Meshlab result.

Anyway, thanks for fast replying.

**Comment by ZhanxyR** [comment]
Also thanks for your interest in our work. Inpaint the large-scale texture directly in UV space usually results in collapse. Sometimes it's better to try with the back-projected result (set `front_only` in the `config.yaml` to False) and mask the incorrect area manually.
