### ISSUE TITLE
Error occurred

### ISSUE THREAD

**Issue by ForrestPi** [ZhanxyR/SHERT#6]
File "/home/code/SHERT/lib/datasets/InpaintEvalDataset.py", line 73, in __getitem__
    displacement = projection_length(sns_vertices - smplx_vertices, smplx_normals)
ValueError: operands could not be broadcast together with shapes (1051,3) (149921,3) 

could you provide some tips?

**Comment by ZhanxyR** [comment]
Could you provide some more infomation, e.g. are you using the demo data or your own data. All of the 3 vars should have the same shape (149921, 3), pls check which one is wrong.

**Comment by ForrestPi** [comment]
@ZhanxyR  
yeah I just used the demo data.

python -m apps.quick_demo -e image

**Comment by ZhanxyR** [comment]
Please check the 3 vars (`sns_vertices, smplx_vertices, smplx_normals`).
And check the SNS result in `demo_*/results` to see if it looks good or weird. 
Which version of Open3D do you use.

**Comment by puppy9207** [comment]
I also had this problem, but I fixed it after reinstalling open3d==0.10.0
```
pip install open3d==0.10.0
```
